apiVersion: ecr.aws.crossplane.io/v1beta1
kind: Repository
metadata:
  name: example
  labels:
    region: eu-west-1
spec:
  forProvider:
    region: eu-west-1
    imageScanningConfiguration:
      scanOnPush: false
    imageTagMutability: IMMUTABLE
  providerConfigRef:
    name: aws-provider
