apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xregistries.aws.tap.example.com
spec:
  group: aws.tap.example.com
  names:
    kind: XRegistry
    plural: xregistries
  claimNames:
    kind: Registry
    plural: registries
  k :
    name: tap-ecr-registry
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              codeName: 
                type: string
              region:
                type: string
            required:
            - codeName
            - region
         