apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: ylcluster
spec:
  providerConfigRef:
    name: azure-upjet-provider
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
    dnsPrefix: tap
    identity:
      - type: SystemAssigned
    location: Canada Central
    resourceGroupNameRef:
      name: crossplane-example-upjet-azure-rg
    tags:
      Environment: Production
