---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-upjet
spec:
  package: xpkg.upbound.io/upbound/provider-gcp:v0.29.0

#
# You can deploy the provider by using kubectl apply -f gcp-provider.yaml
# Use kubectl get providers to determine the status of the provider
# At first the provider will show status of installed is true and it will 
# take a few minutes for health status to go from Unknown to true
# 
# More details:
# https://marketplace.upbound.io/providers/upbound/provider-gcp/
#
