---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
 name: provider-aws
spec:
 package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.38.0

# You can deploy the provider by using kubectl apply -f aws-provider.yaml
# Use kubectl get providers to determine the status of the provider
# At first the provider will show status of installed is true and it will 
# take a few minutes for health status to go from Unknown to true
# 