apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-example-upjet-aws-bucket
  labels:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: crossplane-example-upjet-aws-bucket
spec:
  forProvider:
    forceDestroy: true
    region: eu-north-1
  providerConfigRef:
    name: aws-upjet-provider
