apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: tap-eks-cluster      
spec:
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: aks
  group: xp.example.com
  names:
    kind: XTapEksCluster
    plural: xtapeksclusters
  claimNames:
    kind: TapEksCluster
    plural: tapeksclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    additionalPrinterColumns:
    - name: clusterName
      type: string
      jsonPath: ".status.clusterName"
    - name: controlPlane
      type: string
      jsonPath: ".status.controlPlaneStatus"
    - name: nodePool
      type: string
      jsonPath: ".status.nodePoolStatus"
    - name: fargateProfile
      type: string
      jsonPath: ".status.fargateProfileStatus"
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: Cluster ID that other objects refer to
              parameters:
                type: object
                properties:
                  version:
                    description: Supported by provider Kubernetes version
                    type: string
                  region:
                    description: Cloud region for provisioned resources
                    type: string
                    default: use1
                  nodeSize:
                    description: The node's size; supported; small, medium, large
                    type: string
                    default: small
                  nodeCount:
                    description: The desired number of nodes
                    type: integer
                    default: 1
                  fargateNamespace:
                    description: The Namespace for Fargate Profile
                    type: string
                    default: default
                  registryHost:
                    description: The Hostname for the Tanzu Cluster Essentials registry
                    type: string
                    default: YOUR_REGISTRY_HOST
                  profile:
                    description: Tanzu App Platform profile to install (only "run" is supported currently)
                    type: string
                    default: "run"
                required:
                - version
            required:
            - id
            - parameters
          status:
            type: object
            properties:
              clusterName:
                description: The cluster name
                type: string
              controlPlaneStatus:
                description: The control plane status
                type: string
              nodePoolStatus:
                description: The node pool status
                type: string
              fargateProfileStatus:
                description: The Fargate Profile status
                type: string
              accountID:
                description: AWS account ID
                type: string
              oidcIssuerID:
                description: OIDC issuer ID, no url scheme
                type: string
              oidcIssuerURL:
                description: OIDC issuer URL
                type: string
   
