apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdeployments.aws.tap.example.com
spec:
  group: aws.tap.example.com
  names:
    kind: XDeployment
    plural: xdeployments
  claimNames:
    kind: Deployment
    plural: deployments
  defaultCompositionRef:
    name: tap-aws-deployment
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              codeName: 
                type: string
                description: |
                  a short string that is prefixed orsuffixed to names of 
                  cloud resources that are part of the TAP deployment. It is
                  also used to tag  cloud resoures to easily find all the 
                  resources that are part of the deployment. 
              region: 
                type: string
                description: The region to create ECR tap repos in
              installNamespace: 
                type: string
                description: | 
                  the namespace used to store secrets, and run jobs that are
                  required to complete the installation.
              tanzuNetSecret: 
                type: string
                description: |
                  name of the secret to access the tanzu network to get container
                  images from. The sceret must exist in the installNamespace
              version: 
                type: object
                description: the versions of TAP components to install 
                properties: 
                  tap:
                    type: string
                    description: the version of TAP to install
                  cluster-essentials: 
                    type: string
                    description: the version of cluster essentials to install
                required: 
                - tap
                - cluster-essentials
            required:
            - codeName
            - region 
            - installNamespace
            - tanzuNetSecret
            - version

            
