apiVersion: aws.tap.example.com/v1alpha1
kind: XDeployment
metadata: 
  name: green-tap
spec: 
  codeName: green-tap
  region: us-east-2
  clusters: 
    view: 
      kubernetes: 
        version: "1.25"
        nodeCount: 3
        machineType: m5a.xlarge
  #   build: 
  #     kubernetes: 
  #       version: "1.25"
  #       nodeCount: 3
  #       machineType: m5a.xlarge
  #   iterate: 
  #     kubernetes: 
  #       version: "1.25"
  #       nodeCount: 3
  #       machineType: m5a.xlarge
  #   run-primary: 
  #     kubernetes: 
  #       version: "1.25"
  #       nodeCount: 3
  #       machineType: m5a.xlarge



  installNamespace: green-tap-install
  tanzuNetSecret: tanzunet
  version:
    tap: "1.5.0-rc.20"
    cluster-essentials: "2354688e46d4bb4060f74fca069513c9b42ffa17a0a6d5b0dbb81ed52242ea44"