
#!
#! define jobs to copy images
#!

#@ def patchJobNamespace():
type: FromCompositeFieldPath
toFieldPath: spec.forProvider.manifest.metadata.namespace
fromFieldPath: spec.jobNamespace
#@ end

#@ def installScript():
name: install-script
base:
  apiVersion: kubernetes.crossplane.io/v1alpha1
  kind: Object
  metadata:
    name: install-cluster-essentials-script
  spec:
    forProvider:
      manifest:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: install-cluster-essentials-script
          namespace: ""
        data:
          install.sh: |
            echo "----------------------START--------------------------------"
            echo ""
            echo "--- Environment variables"
            echo "AWS_SHARED_CREDENTIALS_FILE=${AWS_SHARED_CREDENTIALS_FILE}"
            echo "REGION=${REGION}"

            echo ""
            echo "--- Checking aws creds file"
            ls -lah /aws/credentials

            echo ""
            echo "--- configure aws cli"
            aws configure
            ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
            echo "ACCOUNT_ID=${ACCOUNT_ID}"

            export IMGPKG_REGISTRY_HOSTNAME_0=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
            export IMGPKG_REGISTRY_USERNAME_0=AWS
            export IMGPKG_REGISTRY_PASSWORD_0=$(aws ecr get-login-password --region ${REGION})
 
            echo ""
            echo "--- pulling cluster essentials bundle"
            INSTALL_BUDNLE=${IMGPKG_REGISTRY_HOSTNAME_0}/${REPO_NAME}
            echo "bundle repo: ${INSTALL_BUDNLE}"
            imgpkg pull -b $INSTALL_BUNDLE -o /tmp/bundle/
            ls -lha /tmp/bundle
          
           

            # /usr/local/bin/imgpkg copy -b \
            #   ${FROM_REPO} \
            #   --to-repo ${TO_REPO} \
            #   --concurrency 1 \
            #   --include-non-distributable-layers \
            #   --tty
           
            echo ""
            echo "----------------------FINISH--------------------------------"
    providerConfigRef:
      name:  local-kubernetes-provider
patches:
  - #@ patchJobNamespace()
#@ end

#@ def regionPatch(toFieldPath):
type: FromCompositeFieldPath
toFieldPath: #@ toFieldPath
fromFieldPath: spec.region
#@ end

#@ def toRepoNamePatch(toFieldPath):
type: CombineFromComposite
toFieldPath: #@ toFieldPath
combine:
  variables:
    - fromFieldPath: spec.codeName
    - fromFieldPath: spec.toRepoName
  strategy: string
  string:
    fmt: "%s-%s"
#@ end


#@ def fromRepoNamePatch(toFieldPath):
type: FromCompositeFieldPath
toFieldPath: #@ toFieldPath
fromFieldPath: spec.fromRepoUrl
#@ end

#@ def tanzuNetSecretPatch(toFieldPath):
type: FromCompositeFieldPath
toFieldPath: #@ toFieldPath
fromFieldPath: spec.tanzuNetSecret
#@ end

#@ def jobNamePatch(toFieldPath):
type: CombineFromComposite
toFieldPath: #@ toFieldPath
combine:
  variables:
    - fromFieldPath: spec.codeName
    - fromFieldPath: spec.toRepoName
  strategy: string
  string:
    fmt: "%s-copy-images-to-%s"
#@ end


#@ def copyJob():
name: imgpkg-copy
base:
  apiVersion: kubernetes.crossplane.io/v1alpha1
  kind: Object
  metadata:
    #! nameGenerator: #@ "copy-" + repoName + "-"
    name: ""
  spec:
    forProvider:
      manifest:
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: ""
          namespace: ""
        spec:
          backoffLimit: 0
          activeDeadlineSeconds: 3600
          ttlSecondsAfterFinished: 3600
          template:
            spec:
              restartPolicy: Never
              volumes:
                - name: scripts-volume
                  configMap:
                    name: copy-image-script
                - name: aws-access-key
                  secret:
                    secretName: aws-upjet-provider-creds
              containers:
              - name: relocate-images
                image: ghcr.io/asaikali/tap-shell:main
                command: ["/bin/bash"]
                args:
                - /scripts/imgpkg-copy.sh
                securityContext:
                  runAsUser: 1000
                resources:
                  requests:
                    cpu: "1000m"
                    memory: "512Mi"
                volumeMounts:
                - name: scripts-volume
                  mountPath: /scripts
                - name: aws-access-key
                  mountPath: /aws/credentials
                env:
                - name: REGION
                  value: ""
                - name: REPO_NAME
                  value: ""
                - name: FROM_REPO
                  value: ""
                - name: IMGPKG_REGISTRY_HOSTNAME_0
                  value: registry.tanzu.vmware.com
                - name: IMGPKG_REGISTRY_USERNAME_0
                  valueFrom:
                    secretKeyRef:
                      name: ""
                      key: username
                      optional: false
                - name: IMGPKG_REGISTRY_PASSWORD_0
                  valueFrom:
                    secretKeyRef:
                      name: ""
                      key: password
                      optional: false
                - name: AWS_SHARED_CREDENTIALS_FILE
                  value: /aws/credentials/creds

    providerConfigRef:
      name: local-kubernetes-provider
patches:
  - #@ patchJobNamespace()
  - #@ jobNamePatch(toFieldPath="metadata.name")
  - #@ jobNamePatch(toFieldPath="spec.forProvider.manifest.metadata.name")
  - #@ regionPatch      (toFieldPath="spec.forProvider.manifest.spec.template.spec.containers[0].env[0].value")
  - #@ toRepoNamePatch  (toFieldPath="spec.forProvider.manifest.spec.template.spec.containers[0].env[1].value")
  - #@ fromRepoNamePatch(toFieldPath="spec.forProvider.manifest.spec.template.spec.containers[0].env[2].value")
  - #@ tanzuNetSecretPatch(toFieldPath="spec.forProvider.manifest.spec.template.spec.containers[0].env[4].valueFrom.secretKeyRef.name")
  - #@ tanzuNetSecretPatch(toFieldPath="spec.forProvider.manifest.spec.template.spec.containers[0].env[5].valueFrom.secretKeyRef.name")
#@ end

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tap-install-cluster-essentials
  labels:
    crossplane.io/xrd: xclusteressentialsjobs.aws.tap.example.com
spec:
  compositeTypeRef:
    apiVersion: aws.tap.example.com/v1alpha1
    kind: XClusterEssentialsJob
  resources:
  - #@ installScript()