apiVersion: aws.tap.example.com/v1alpha1
kind: XClusterEssentialsJob
metadata: 
  name: green-tap
spec: 
  codeName: green-tap
  region: us-east-2
  repoName: cluster-essentials
  version: "79abddbc3b49b44fc368fede0dab93c266ff7c1fe305e2d555ed52d00361b446"
  jobNamespace: crossplane-system
